package com.fersaiyan.cyanbridge.localmodels.catalog

data class LocalModelCatalogEntry(
    val id: String,
    val displayName: String,
    val family: String,
    val providerType: String = "local",
    val engine: String = "llama",
    val format: String = "gguf",
    val sourceUrl: String?,
    val sourcePageUrl: String?,
    val expectedFilename: String,
    val sha256: String?,
    val sizeBytes: Long,
    val quantization: String,
    val contextSizeDefault: Int,
    val promptTemplateId: String,
    val minRamGb: Double,
    val minStorageGb: Double,
    val shortDescription: String,
    val tags: List<String>,
    val gatedDownload: Boolean,
    val licenseTermsNote: String,
    val enabled: Boolean,
    val npuSupported: Boolean = false,
    val npuOnly: Boolean = false,
    val comingSoon: Boolean = false,
)

object LocalModelCatalogRepository {
    val curatedModels: List<LocalModelCatalogEntry> = listOf(
        LocalModelCatalogEntry(
            id = "gemma4-e2b-it-litert",
            displayName = "Gemma 4 E2B IT (LiteRT-LM)",
            family = "gemma",
            engine = "litert",
            format = "litertlm",
            sourceUrl = "https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm/resolve/main/gemma-4-E2B-it.litertlm",
            sourcePageUrl = "https://huggingface.co/litert-community/gemma-4-E2B-it-litert-lm",
            expectedFilename = "gemma-4-E2B-it.litertlm",
            sha256 = null,
            sizeBytes = 2_580_000_000L,
            quantization = "MIXED (2/4/8-bit)",
            contextSizeDefault = 4096,
            promptTemplateId = "gemma_it",
            minRamGb = 8.0,
            minStorageGb = 4.5,
            shortDescription = "Latest Gemma 4 LiteRT-LM package with stronger on-device quality.",
            tags = listOf("litert", "gemma4", "quality", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Gemma model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "gemma4-e4b-it-litert",
            displayName = "Gemma 4 E4B IT (LiteRT-LM)",
            family = "gemma",
            engine = "litert",
            format = "litertlm",
            sourceUrl = "https://huggingface.co/litert-community/gemma-4-E4B-it-litert-lm/resolve/main/gemma-4-E4B-it.litertlm",
            sourcePageUrl = "https://huggingface.co/litert-community/gemma-4-E4B-it-litert-lm",
            expectedFilename = "gemma-4-E4B-it.litertlm",
            sha256 = null,
            sizeBytes = 3_650_000_000L,
            quantization = "MIXED (4/8-bit)",
            contextSizeDefault = 4096,
            promptTemplateId = "gemma_it",
            minRamGb = 8.0,
            minStorageGb = 6.5,
            shortDescription = "Gemma 4 E4B LiteRT-LM package for higher quality on high-memory devices.",
            tags = listOf("litert", "gemma4", "quality", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Gemma model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "qwen2.5-1.5b-instruct-q4",
            displayName = "Qwen2.5 1.5B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF/resolve/main/qwen2.5-1.5b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-1.5B-Instruct-GGUF",
            expectedFilename = "qwen2.5-1.5b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 1_210_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 8.0,
            minStorageGb = 2.3,
            shortDescription = "Higher quality small model for stronger phones.",
            tags = listOf("quality", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "qwen2.5-0.5b-instruct-q4",
            displayName = "Qwen2.5 0.5B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF/resolve/main/qwen2.5-0.5b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-0.5B-Instruct-GGUF",
            expectedFilename = "qwen2.5-0.5b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 491_400_032L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 4.0,
            // Download headroom is checked separately; loading only needs working-file space.
            minStorageGb = 0.35,
            shortDescription = "Fast starter model for offline replies and short reasoning.",
            tags = listOf("fast", "offline", "starter"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "qwen2.5-3b-instruct-q4",
            displayName = "Qwen2.5 3B Instruct (Q4_K_M)",
            family = "qwen",
            sourceUrl = "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF/resolve/main/qwen2.5-3b-instruct-q4_k_m.gguf",
            sourcePageUrl = "https://huggingface.co/Qwen/Qwen2.5-3B-Instruct-GGUF",
            expectedFilename = "qwen2.5-3b-instruct-q4_k_m.gguf",
            sha256 = null,
            sizeBytes = 1_910_000_000L,
            quantization = "Q4_K_M",
            contextSizeDefault = 4096,
            promptTemplateId = "qwen_chat",
            minRamGb = 8.0,
            minStorageGb = 3.0,
            shortDescription = "Stronger Qwen model for better response quality on newer phones.",
            tags = listOf("balanced", "quality", "offline"),
            gatedDownload = false,
            licenseTermsNote = "Use under Qwen model license terms.",
            enabled = true,
        ),
        LocalModelCatalogEntry(
            id = "gemma4-e2b-npu-coming-soon",
            displayName = "Gemma 4 E2B (NPU - Coming Soon)",
            family = "gemma",
            engine = "litert",
            format = "litertlm",
            sourceUrl = null,
            sourcePageUrl = "https://huggingface.co/litert-community",
            expectedFilename = "gemma-4-E2B-npu.litertlm",
            sha256 = null,
            sizeBytes = 2_400_000_000L,
            quantization = "NPU AOT (QNN/INT4)",
            contextSizeDefault = 4096,
            promptTemplateId = "gemma_it",
            minRamGb = 8.0,
            minStorageGb = 4.0,
            shortDescription = "Snapdragon NPU Ahead-of-Time (AOT) compiled package. Coming soon for Snapdragon 8 Gen 2/3/4.",
            tags = listOf("npu", "gemma4", "coming_soon"),
            gatedDownload = false,
            licenseTermsNote = "Use under Gemma model license terms.",
            enabled = false,
            npuSupported = true,
            npuOnly = true,
            comingSoon = true,
        ),
    )

    fun findById(id: String?): LocalModelCatalogEntry? {
        if (id.isNullOrBlank()) return null
        return curatedModels.firstOrNull { it.id == id }
    }
}
